apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog
resources:
- api-key-secret.yaml
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- datadog-agent-logs-apm.yaml
- namespace.yaml